import 'dart:convert';

import 'package:audioplayers/audioplayers.dart';
import 'package:flutter/services.dart' show rootBundle;

/// Plays bundled pronunciation audio (`assets/audio/<token>.mp3`).
///
/// Which files exist is declared in assets/audio/manifest.json, generated by
/// tool/generate_igbo_audio.py. [hasAudio] is cached after the first read;
/// [play] is a safe no-op when the manifest is empty, so the app runs fine
/// before any audio has been generated.
class AudioService {
  AudioService._();

  static final AudioPlayer _player = AudioPlayer();
  static Set<String>? _files;

  static Future<Set<String>> _availableFiles() async {
    var cached = _files;
    if (cached != null) return cached;
    try {
      final raw = await rootBundle.loadString('assets/audio/manifest.json');
      final data = jsonDecode(raw) as Map<String, dynamic>;
      final files = (data['files'] as List<dynamic>).cast<String>();
      cached = files.map((f) => f.replaceFirst('.mp3', '')).toSet();
    } catch (_) {
      cached = const <String>{};
    }
    _files = cached;
    return cached;
  }

  /// Whether a bundled audio clip exists for the given Igbo text token.
  static Future<bool> hasAudio(String token) async {
    return (await _availableFiles()).contains(tokenKey(token));
  }

  /// Plays the clip for [token] when it exists; does nothing otherwise.
  static Future<void> play(String token) async {
    if (!await hasAudio(token)) return;
    await _player.stop();
    await _player.play(AssetSource('audio/${tokenKey(token)}'));
  }

  /// File-name key for a token: trimmed, lowercased, spaces to underscores,
  /// diacritics preserved.
  static String tokenKey(String token) {
    return token.trim().toLowerCase().replaceAll(RegExp(r'\s+'), '_');
  }
}
